apply plugin: 'maven-publish'

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version
            artifact(jar) {
                builtBy project.provider { project.tasks.named('reobfJar') }
            }
            if (mod.sources) {
                artifact(sourceJar)
            }
            pom {
                licenses {
                    license {
                        name = mod.license
                        url = mod.license_url.toString()
                    }
                }
            }
        }
    }
    repositories {
        maven {
            if ('remote_maven' in mod) {
                url mod.maven
                credentials(PasswordCredentials)
            } else if ('local_maven' in mod) {
                url mod.local_maven
            }
        }
    }
}
publish.dependsOn('reobfJar')
