apply plugin: 'net.darkhax.curseforgegradle'

String curseChangelog = mod.gitChangelog()
task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    if ('curse_auth' in secrets) {
        apiToken = secrets.curse_auth.toString()
    } else if (System.getenv('CURSEFORGE_UPLOAD_TOKEN')) {
        apiToken = System.getenv('CURSEFORGE_UPLOAD_TOKEN')
    } else {
        apiToken = ''
    }
    
    Closure fileConfig = { file ->
        file.releaseType = mod.curse.release
        file.changelog = curseChangelog
        file.changelogType = 'markdown'
        mod.curse.requirements.each { file.addRequirement(it) }
        mod.curse.optionals.each { file.addOptional(it) }
    }
    
    def mainFile = upload(mod.curse.project, jar)
    switch (mod.curse.environment_type) {
        case 'client_only': mainFile.addEnvironment('Client'); break
        case 'server_only': mainFile.addEnvironment('Server'); break
        default: mainFile.addEnvironment('Client', 'Server'); break // optionals are treated as "supported"
    }
    fileConfig(mainFile)
    
    if (mod.sources) {
        def sourcesFile = mainFile.withAdditionalFile(sourceJar)
        fileConfig(sourcesFile)
    }
}
project.tasks.getByName('curseforge').dependsOn('reobfJar')
